using System;
using System.Collections.Generic;
using System.IO;

public class SP_Code_Generator
{
    public void GeneraFileDiTesto(List<string> configurazioni, string filePath)
    {
        // Controlla se il file esiste già e, se esiste, lo cancella
        if (File.Exists(filePath))
        {
            File.Delete(filePath);  // Elimina il file esistente
        }

        using (StreamWriter sw = new StreamWriter(filePath))
        {
            sw.WriteLine("/**************************************************************************************************");
            sw.WriteLine(" * (C) 2024 STEM         ");
            sw.WriteLine(" * All rights reserved.  ");
            sw.WriteLine($" * Generation Time: {DateTime.Now:dd MMM yyyy HH:mm:ss} "); // Data e ora corrente
            sw.WriteLine(" **************************************************************************************************/");
            sw.WriteLine("/*");
            sw.WriteLine(" * SP_Config.h");
            sw.WriteLine(" *");
            sw.WriteLine(" *  Generated by STEM Protocol Manager");
            sw.WriteLine(" */");
            sw.WriteLine("#ifndef SP_CONFIG_H_");
            sw.WriteLine("#define SP_CONFIG_H_");
            sw.WriteLine();
            sw.WriteLine("/**************************************************************************************************");
            sw.WriteLine(" *  DEFINES  ");
            sw.WriteLine(" **************************************************************************************************/");

            // Scrittura delle configurazioni
            foreach (var config in configurazioni)
            {
                if (config.Contains("="))
                {
                    var parts = config.Split('=');
                    sw.WriteLine($"#define {parts[0].Trim()} {parts[1].Trim()}");
                }
                else
                {
                    sw.WriteLine($"#define {config.Trim()}");
                }
            }

            // Aggiungi commenti finali, typedef, e altre definizioni
            sw.WriteLine();
            sw.WriteLine("/**************************************************************************************************");
            sw.WriteLine(" *  PUBLIC TYPES  ");
            sw.WriteLine(" **************************************************************************************************/");
            sw.WriteLine(" typedef enum{");
            sw.WriteLine("     BLE_SERIAL = 0,");
            sw.WriteLine("     CAN_BUS_1,");
            sw.WriteLine("     CAN_BUS_2");
            sw.WriteLine(" }RouterChannel_t;");
            sw.WriteLine();
            sw.WriteLine("#endif /* SP_CONFIG_H_ */");
            sw.WriteLine("/**************************************************************************************************");
            sw.WriteLine(" *  EOF         ");
            sw.WriteLine(" **************************************************************************************************/");
        }
    }
}